_target_: src.models.bi_encoder_module.BiEncoderSpeechTextModule
lr: 0.001
weight_decay: 0.0005
criterion: TripletLoss
trainable_layers: 1

model:
  _target_: src.models.components.encoder_components.BiEncoderSpeechTextModel
  pretrained_speech_model: ntu-spml/distilhubert
  pretrained_text_model: google/bert_uncased_L-2_H-768_A-12