# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: conceptual.yaml
  - model: flat_perceiver.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml # TODO testing should be done on one device, helps reproducibility: https://pytorch-lightning.readthedocs.io/en/latest/common/evaluation_intermediate.html#test-after-fit
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ???