_target_: src.datamodules.cococaptions_datamodule.COCOCaptionsDatamodule

data_dir: ${data_dir}/mscoco # data_dir is specified in train.yaml or test.yaml
train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
pin_memory: True