_target_: src.datamodules.conceptual_datamodule.ConceptualCaptionsDataModule

data_dir:  # ${data_dir}/conceptual # data_dir is specified in train.yaml or test.yaml # E:/Datasets
train_batch_size: 128
val_batch_size: 100
test_batch_size: 100
pin_memory: True
