_target_: src.datamodules.tinyimagenet_datamodule.TinyImagenetDataModule

data_dir: ${data_dir}/tiny_imagenet_200 # data_dir is specified in train.yaml or test.yaml
num_workers: 0
batch_size: 32
shuffle: True
pin_memory: True
drop_last: False
