_target_: src.datamodules.librispeech_datamodule.WikipediaDatamoduel

data_dir: ${data_dir}/wikipedia # data_dir is specified in train.yaml or test.yaml
max_input_length: 8192
train_batch_size: 256
val_batch_size: 100
test_batch_size: 100
train_on_long_form_text: False
pin_memory: True
